test

diff --git a/.github/workflows/wokwi.yml b/.github/workflows/wokwi.yml
--- a/.github/workflows/wokwi.yml
+++ b/.github/workflows/wokwi.yml
@@ -13,6 +13,111 @@ env:
   WOKWI_TIMEOUT: 600000 # Milliseconds
 
 jobs:
+  get-artifacts:
+    name: Get required artifacts
+    runs-on: ubuntu-latest
+    outputs:
+      ref: ${{ steps.set-ref.outputs.ref }}
+    steps:
+      - name: Report pending
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const owner = '${{ github.repository_owner }}';
+            const repo = '${{ github.repository }}'.split('/')[1];
+            const sha = '${{ github.event.workflow_run.head_sha }}';
+            core.debug(`owner: ${owner}`);
+            core.debug(`repo: ${repo}`);
+            core.debug(`sha: ${sha}`);
+            const { context: name, state } = (await github.rest.repos.createCommitStatus({
+              context: 'Runtime Tests / Wokwi (Get artifacts) (${{ github.event.workflow_run.event }} => workflow_run)',
+              owner: owner,
+              repo: repo,
+              sha: sha,
+              state: 'pending',
+              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+            })).data;
+            core.info(`${name} is ${state}`);
+
+      - name: Download and extract event file
+        uses: actions/download-artifact@v4
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ github.event.workflow_run.id }}
+          name: event_file
+          path: artifacts/event_file
+
+      - name: Try to read PR number
+        id: set-ref
+        run: |
+          ref=$(jq -r '.pull_request.number' artifacts/event_file/event.json)
+          if [ -z "$ref" ] || [ "$ref" == "null" ]; then
+            ref=${{ github.ref }}
+          fi
+
+          echo "ref = $ref"
+          printf "${{ github.event.workflow_run.event }}" >> artifacts/event.txt
+          printf "Event name = "
+          cat artifacts/event.txt
+          printf "${{ github.event.workflow_run.head_sha || github.sha }}" >> artifacts/sha.txt
+          printf "Head SHA = "
+          cat artifacts/sha.txt
+
+          if [ -z "$ref" ] || [ "$ref" == "null" ]; then
+            echo "Failed to get PR number or ref"
+            exit 1
+          fi
+
+          echo "ref=$ref" >> $GITHUB_OUTPUT
+
+      - name: Download and extract parent hardware results
+        uses: actions/download-artifact@v4
+        continue-on-error: true
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ github.event.workflow_run.id }}
+          pattern: tests-results-hw-*
+          merge-multiple: true
+          path: artifacts/results/hw
+
+      - name: Download and extract parent QEMU results
+        uses: actions/download-artifact@v4
+        continue-on-error: true
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          run-id: ${{ github.event.workflow_run.id }}
+          pattern: tests-results-qemu-*
+          merge-multiple: true
+          path: artifacts/results/qemu
+
+      - name: Upload parent artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: parent-artifacts
+          path: artifacts
+          if-no-files-found: error
+
+      - name: Report conclusion
+        uses: actions/github-script@v7
+        if: always()
+        with:
+          script: |
+            const owner = '${{ github.repository_owner }}';
+            const repo = '${{ github.repository }}'.split('/')[1];
+            const sha = '${{ github.event.workflow_run.head_sha }}';
+            core.debug(`owner: ${owner}`);
+            core.debug(`repo: ${repo}`);
+            core.debug(`sha: ${sha}`);
+            const { context: name, state } = (await github.rest.repos.createCommitStatus({
+              context: 'Runtime Tests / Wokwi (Get artifacts)',
+              owner: owner,
+              repo: repo,
+              sha: sha,
+              state: '${{ job.status }}',
+              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+            })).data;
+            core.info(`${name} is ${state}`);
+
   wokwi-test:
     name: Wokwi ${{ matrix.chip }} ${{ matrix.type }} tests
     if: |
@@ -20,8 +125,9 @@ jobs:
       github.event.workflow_run.conclusion == 'failure' ||
       github.event.workflow_run.conclusion == 'timed_out'
     runs-on: ubuntu-latest
+    needs: get-artifacts
     env:
-      id: ${{ github.event.workflow_run.head_sha }}-${{ matrix.chip }}-${{ matrix.type }}
+      id: ${{ needs.get-artifacts.outputs.ref }}-${{ github.event.workflow_run.head_sha || github.sha }}-${{ matrix.chip }}-${{ matrix.type }}
     permissions:
       actions: read
       statuses: write
@@ -42,7 +148,7 @@ jobs:
             core.debug(`repo: ${repo}`);
             core.debug(`sha: ${sha}`);
             const { context: name, state } = (await github.rest.repos.createCommitStatus({
-              context: 'Runtime Tests / Wokwi (${{ matrix.type }}, ${{ matrix.chip }})',
+              context: 'Runtime Tests / Wokwi (${{ matrix.type }}, ${{ matrix.chip }}) (${{ github.event.workflow_run.event }} => workflow_run)',
               owner: owner,
               repo: repo,
               sha: sha,
@@ -51,7 +157,7 @@ jobs:
             })).data;
             core.info(`${name} is ${state}`);
 
-      - name: Check if already run
+      - name: Check if already passed
         id: get-cache-results
         uses: actions/cache/restore@v4
         with:
@@ -73,24 +179,10 @@ jobs:
 
           echo "enabled=$enabled" >> $GITHUB_OUTPUT
 
-      - name: Checkout user repository
+      # Note that changes to the workflows and tests will only be picked up after the PR is merged
+      - name: Checkout repository
         if: ${{ steps.check-tests.outputs.enabled == 'true' }}
         uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.workflow_run.head_sha }}
-          persist-credentials: false
-          sparse-checkout-cone-mode: false
-          sparse-checkout: |
-            /*
-            !.github
-
-      # To avoid giving unknown scripts elevated permissions, download them from the master branch
-      - name: Get CI scripts from master
-        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
-        run: |
-          mkdir -p .github
-          cd .github
-          curl https://codeload.github.com/${{ github.repository }}/tar.gz/master | tar -xz --strip=2 arduino-esp32-master/.github
 
       - uses: actions/setup-python@v5
         if: ${{ steps.check-tests.outputs.enabled == 'true' }}
@@ -113,24 +205,6 @@ jobs:
         if: ${{ steps.check-tests.outputs.enabled == 'true' }}
         uses: wokwi/wokwi-ci-server-action@v1
 
-      # - name: Download and Extract Artifacts
-      #   run: |
-      #     artifacts_url=${{ github.event.workflow_run.artifacts_url }}
-      #     gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
-      #     do
-      #       IFS=$'\t' read name url <<< "$artifact"
-      #       gh api $url > "$name.zip"
-      #       unzip -j "$name.zip" -d "temp_$name"
-      #       if [[ "$name" == "pr_number" ]]; then
-      #         mv "temp_$name"/* workflows
-      #       else
-      #         mv "temp_$name"/* libraries-report
-      #       fi
-      #       rm -r "temp_$name"
-      #     done
-      #     echo "Contents of parent directory:"
-      #     ls -R ..
-
       - name: Get binaries
         if: ${{ steps.check-tests.outputs.enabled == 'true' }}
         uses: actions/download-artifact@v4
@@ -150,7 +224,7 @@ jobs:
 
       - name: Upload ${{ matrix.chip }} ${{ matrix.type }} Wokwi results as cache
         uses: actions/cache/save@v4
-        if: ${{ always() && steps.check-tests.outputs.enabled == 'true' }}
+        if: ${{ steps.check-tests.outputs.enabled == 'true' }}
         with:
           key: tests-${{ env.id }}-results-wokwi
           path: |
